### Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.debug=false

### Toolchain setup
java.version=25

### Project
type=MOD
license=MIT
author=chisels-and-bits
modId=chiselsandbits
description=A Minecraft mod about creating endless custom decorations using in game materials.\n\nWell that's pretty broad, but its accurate, C&B takes existing blocks in your game world and lets you manipulate them together to create new custom creations, sculpting, copying, sawing, rotating, measuring and building is all possible at a micro-scale.\n\nThe possibilities are virtually endless.

### Minecraft
minecraft.version=26.1-snapshot-1
minecraft.additionalVersions=

### Common
common.neoform.version=26.1-snapshot-1-3

### Neoforge
neoforge.version=[26.1.0.0-alpha.3+snapshot-1]
neoforge.data.runs=clientData

### Fabric
fabric.loader.version=[0.18,)
fabric.api.version=0.140.2
fabric.api.minecraft.version=26.1

### Versioning
local.version=26.1-snapshot-1-local

### Dependency versioning
jetbrains.annotations.version=+
communi.suggestu.scena.version=[26.1-snapshot-1.0.7,26.2)
org.lz4.lz4.pure.java.version=1.10.1

### Curse
curse.id.neoforge=231095
curse.id.fabric=561059
curse.minecraft.version=26.1-snapshot