pluginManagement {
    repositories {
        mavenLocal()
        maven {
            url 'https://ldtteam.jfrog.io/artifactory/communi-suggestu-maven'
            name 'Communi-Suggestu Maven'
        }
        maven {
            url 'https://ldtteam.jfrog.io/artifactory/tableau'
            name 'Tableau Maven'
        }
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'NeoForged'
            url = 'https://maven.neoforged.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }

    if (file('../Chisels-And-Bits-Website').exists()) {
        includeBuild '../Chisels-And-Bits-Website'
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
    id 'com.communi-suggestu.placitum' version '0.0.76'
}

rootProject.name = "chisels-and-bits"

platforms {
    common(':api')
    core(':core')
    modernFabric(':fabric')
    neoforge(':neoforge')

    defaults {
        java {
            version = 25
        }
        project {
            owner = "chisels-and-bits"
        }
    }
}